# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gusztavvargadr/ubuntu-desktop"

  # VM srv02
  config.vm.define "srv02"  do |srv02|

    # VARIABLE HOSTNAME
    APP_NAME= "ubuntu-srv02"

    # HOSTNAME
    srv02.vm.hostname = APP_NAME

    # NETWORK
    srv02.vm.network "public_network" ,ip: "192.168.0.133",mode: "bridge"

    # Forward Port
    # srv02.vm.network "forwarded_port", guest: 8020, host: 9020, adapter: 1, guest_ip: "192.168.0.133" ,host_ip: "192.168.0.33"
    # srv02.vm.network "forwarded_port", guest: 2234, host: 3234, adapter: 1, guest_ip: "192.168.0.133" ,host_ip: "192.168.0.33"

    # MOUNTS
    srv02.vm.synced_folder ".", "/vagrant", disabled: true
    srv02.vm.synced_folder "./security", "/security"
    #srv02.vm.synced_folder "./install", "/totvs/install", type: "rsync",rsync__args: ["-r", "--include=*"]

    # PROVIDER
    srv02.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 2048
      vb.cpus = 1
    end

    # PROVISION
    srv02.vm.provision "shell", inline: <<-SHELL
      cat /security/id_rsa.pub >> .ssh/authorized_keys
      cd  /tmp
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt install ./google-chrome-stable_current_amd64.deb

    SHELL

    # # PACKAGES FOR PROVISION
    # srv02.vm.provision "shell", inline: <<-SHELL
    #   dnf install python3 -y
    # SHELL

  end

end